import type { ProjectDTO } from "@/modules/project/dto";

export const mock: ProjectDTO[] = [
	{
		id: "1",
		title: "source anything birds",
		slug: "source-anything-birds",
		summary: "Summary 1",
		impact: "Impact 1",
		content: "# Content 1\nMore content",
		highlights: [],
		category: "fullstack",
		status: "active",
		tech: ["Tech 1", "Tech 2"],
		repositoryUrl: "https://github.com/username/project-1",
		liveUrl: "https://project-1.com",
		visible: true,
		createdAt: "2023-01-01T00:00:00Z",
		updatedAt: "2023-01-01T00:00:00Z",
	},
	{
		id: "2",
		title: "except center courage",
		slug: "except-center-courage",
		summary: "Summary 2",
		impact: "Impact 2",
		content: "# Content 2\nMore content",
		highlights: [
			{
				id: "h1",
				content: "Highlight 1",
				sortOrder: 1,
			},
			{
				id: "h2",
				content: "Highlight 2",
				sortOrder: 2,
			},
		],
		category: "backend",
		status: "active",
		tech: ["Tech 1", "Tech 2"],
		repositoryUrl: "https://github.com/username/project-2",
		liveUrl: "https://project-2.com",
		visible: true,
		createdAt: "2023-01-01T00:00:00Z",
		updatedAt: "2023-01-01T00:00:00Z",
	},
	{
		id: "3",
		title: "price block animal",
		slug: "price-block-animal",
		summary: "Summary 3",
		impact: "Impact 3",
		content: "# Content 3\nMore content",
		highlights: [],
		category: "frontend",
		status: "active",
		tech: ["Tech 1", "Tech 2"],
		repositoryUrl: "https://github.com/username/project-3",
		liveUrl: "https://project-3.com",
		visible: true,
		createdAt: "2023-01-01T00:00:00Z",
		updatedAt: "2023-01-01T00:00:00Z",
	},
	{
		id: "4",
		title: "Project 4",
		slug: "project-4",
		summary: "Summary 4",
		impact: "Impact 4",
		content: "# Content 4\nMore content",
		highlights: [],
		category: "cli",
		status: "active",
		tech: ["Tech 1", "Tech 2"],
		repositoryUrl: "https://github.com/username/project-4",
		liveUrl: "https://project-4.com",
		visible: true,
		createdAt: "2023-01-01T00:00:00Z",
		updatedAt: "2023-01-01T00:00:00Z",
	},
];
