import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const src = path.join(__dirname, "..", "src");
const schemasDir = path.join(src, "schemas");
const outputPath = path.join(src, "schema.ts");

// Get all .ts files in the schemas directory (excluding index.ts and subdirectories)
const files = fs
	.readdirSync(schemasDir)
	.filter((file) => file.endsWith(".ts") && file !== "index.ts")
	.sort();

// Generate export statements
const exports = files
	.map((file) => {
		const moduleName = file.replace(".ts", "");
		return `export * from './schemas/${moduleName}';`;
	})
	.join("\n");

// Create the index.ts content
const content = `// Auto-generated file - do not modify manually
// Generated by generate-schema-index.js

${exports}
`;

// Write the index.ts file
fs.writeFileSync(outputPath, content, "utf8");
console.log(`Generated ${outputPath} with ${files.length} schema files`);
